services:
  database:
    image: postgres:18
    ports:
      - '5432:5432'
    env_file:
      - ./database/.env
    healthcheck:
      test: ['CMD', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      retries: 5
      timeout: 10s

  queue-service-test:
    image: blockqueue/bq-queue:latest # for testing the locally built image
    # image: ghcr.io/blockqueue/bq-queue:v0.0.1 # for testing the remote image build
    ports:
      - '9000:9000'
    volumes:
      - ../apps/queue-service/config:/config
    env_file:
      - ../apps/queue-service/.env.test

  queue-service-ui-test:
    image: blockqueue/bq-queue-ui:latest # for testing the locally built image
    # image: ghcr.io/blockqueue/bq-queue-ui:v0.0.1 # for testing the remote image build
    ports:
      - '3000:3000'
    env_file:
      - ./dashboard/.env
