# build prod versions of the queue service and dashboard for quick testing

services:
  bq-queue:
    build:
      context: ../
      dockerfile: ./docker/bq-queue/Dockerfile.prod
    image: blockqueue/bq-queue:latest

  bq-queue-ui:
    build:
      context: ../
      dockerfile: ./docker/dashboard/Dockerfile
    image: blockqueue/bq-queue-ui:latest
